export const endpoints = {
  homepage: "homepage",
  banners: (position: string) => `banners?position=${encodeURIComponent(position)}`,
  products: "products",
  productBySlug: (slug: string) => `products/${encodeURIComponent(slug)}`,
  relatedProducts: (id: number) => `products/${id}/related`,
  productReviews: (id: number, page: number) => `products/${id}/reviews?page=${page}`,
  categories: "categories",
  categoryProducts: (slug: string) => `categories/${encodeURIComponent(slug)}/products`,
  search: (q: string) => `search?q=${encodeURIComponent(q)}`,
  searchSuggest: (q: string) => `search/suggest?q=${encodeURIComponent(q)}`,
  searchTrending: "search/trending",
  cart: "cart",
  cartItems: "cart/items",
  cartItem: (id: number) => `cart/items/${id}`,
  cartApplyCoupon: "cart/apply-coupon",
  cartRemoveCoupon: "cart/remove-coupon",
  cartMerge: "cart/merge",
  checkoutValidate: "checkout/validate-cart",
  checkoutCalculate: "checkout/calculate",
  checkoutPlace: "checkout/place-order",
  checkoutPayment: "checkout/payment/initiate",
  userOrders: "user/orders",
  userOrder: (number: string) => `user/orders/${encodeURIComponent(number)}`,
  authRegister: "auth/register",
  authLogin: "auth/login",
  authLogout: "auth/logout",
  authForgot: "auth/forgot-password",
  authReset: "auth/reset-password",
  authVerify: "auth/verify-phone",
  authResendOtp: "auth/resend-otp",
  wishlist: "user/wishlist",
  wishlistProduct: (productId: number) => `user/wishlist/${productId}`,
  wishlistCheck: (id: number) => `user/wishlist/check/${id}`,
  loyalty: "user/loyalty",
  loyaltyTx: "user/loyalty/transactions",
  reviews: "reviews",
  reviewVote: (id: number) => `reviews/${id}/vote`,
  flashDeals: "flash-deals",
} as const;
